### ISSUE TITLE
Why does the SymbolicPlanners.jl need to be added to the package manager?

### ISSUE THREAD

**Issue by owenps** [JuliaPlanners/SymbolicPlanners.jl#1]
Hi ztangent! 

In the .README, once PDDL.jl is install you ask to run
```
add https://github.com/JuliaPlanners/SymbolicPlanners.jl
```
in the Julia package manager. I understand why you add PDDL as a package but I'm not so confident of the purpose for these planners. 

If you could clarify that would be great! Thanks for all your work.

**Comment by ztangent** [comment]
Oh, those instructions are if you want to use the planners in your own script or package! But if you have cloned a local copy of this repository, then you don't need to do that.

**Comment by ztangent** [comment]
I just noticed that you're working on https://github.com/owenps/ParallelPlanners.jl, which looks really exciting! One thing I'll note is that this codebase is not stable yet and the interfaces may still change considerably. PDDL.jl is also pending a major refactor to enable various pre-compilation tricks to hopefully make everything faster. All of that might end up affecting what you're hoping to do, so I just thought I'd flag that in advance!

**Comment by owenps** [comment]
Thanks for the clarification and support! 😄 It should be a fun project - I'll definitely keep an eye out for new pushes to this repo and PDDL.
