### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by guilherme-puida** [JuliaPlanners/SymbolicPlanners.jl#12]
I've used this (and PDDL.jl) in an university project and would like to properly cite them in the finished article. However, there's currently no [CITATION.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) in this or the other repository.

I've just noticed this and I think it would be a good idea to help others to correctly cite work done by the maintainers. Thanks!

**Comment by ztangent** [comment]
Hi Guilherme, thanks for the suggestion, and glad you found both these libraries useful! I'll plan on adding the CITATION.cff files soon. In the meantime, it'd be great if you could cite this thesis: https://dspace.mit.edu/handle/1721.1/143179

**Comment by guilherme-puida** [comment]
Will do. Thanks for the quick response and for the great libraries :^)

**Comment by ztangent** [comment]
Welcome! :) Just added the CITATION.cff for this repository, and turns out the PDDL.jl repository already had one, so I'm closing this.
